# Generated by Django 6.0.7 on 2026-08-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
